In [1]:
import tensorflow as tf


In [2]:
ref = tf.Variable([[1, 2, 3, 4, 5, 6, 7, 8], 
                   [1, 2, 3, 4, 5, 6, 7, 8]])
indices = tf.constant([[[0, 4], [0, 3], [0, 1], [0, 7], [0, 1]], 
                       [[1, 4], [1, 3], [1, 1], [1, 7], [1, 7]]])
updates = tf.constant([[9, 10, 11, 12, 3], [9, 10, 11, 12, 3]])
add = tf.scatter_nd_add(ref, indices, updates)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print sess.run(add)

[[ 1 16  3 14 14  6  7 20]
 [ 1 13  3 14 14  6  7 23]]


In [3]:
ref = tf.Variable([[1, 2, 3, 4, 5, 6, 7, 8], 
                   [1, 2, 3, 4, 5, 6, 7, 8]])
indices = tf.constant([[[0, 4], [0, 3], [0, 1], [0, 7], [0, 1]], 
                       [[1, 4], [1, 3], [1, 1], [1, 7], [1, 7]]])
updates = tf.constant([[9, 10, 11, 12, 3], [9, 10, 11, 12, 3]])
add = tf.scatter_nd_add(ref, indices, updates)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print sess.run(add)

[[ 1 16  3 14 14  6  7 20]
 [ 1 13  3 14 14  6  7 23]]


In [4]:
indices.shape

TensorShape([Dimension(2), Dimension(5), Dimension(2)])

In [5]:
sess = tf.InteractiveSession()

In [6]:
tf.range(10).eval()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [7]:
d = (tf.transpose(tf.expand_dims(tf.range(2),0)))

In [8]:
d.eval()

array([[0],
       [1]], dtype=int32)

In [9]:
#tf.tile(d, [4,1]).eval()

In [10]:
x = tf.constant([[1,3,5], 
                 [2,4,6]])

In [11]:
x.eval()

array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)

In [12]:
tf.concat([d, x], 1).eval()

array([[0, 1, 3, 5],
       [1, 2, 4, 6]], dtype=int32)

In [13]:
d = tf.tile(d, [1, 3])

In [14]:
d.eval()

array([[0, 0, 0],
       [1, 1, 1]], dtype=int32)

In [15]:
tf.reshape(d, [-1, 1]).eval()

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]], dtype=int32)

In [16]:
tf.reshape(x, [-1, 1]).eval()

array([[1],
       [3],
       [5],
       [2],
       [4],
       [6]], dtype=int32)

In [17]:
d2 = tf.reshape(d, [-1, 1])

In [18]:
x2 = tf.reshape(x, [-1, 1])

In [19]:
tf.concat([d2, x2], 1).eval()

array([[0, 1],
       [0, 3],
       [0, 5],
       [1, 2],
       [1, 4],
       [1, 6]], dtype=int32)

In [20]:
tf.reshape(tf.concat([d2, x2], 1), [2, 3, 2]).eval()

array([[[0, 1],
        [0, 3],
        [0, 5]],

       [[1, 2],
        [1, 4],
        [1, 6]]], dtype=int32)

In [21]:
def batch_values_to_indices(x):
  shape_ = tf.shape(x)
  batch_size = shape_[0]
  num_cols = shape_[1]
  d = tf.transpose(tf.expand_dims(tf.range(batch_size),0))
  d = tf.tile(d, [1, num_cols])
  d_flatten = tf.reshape(d, [-1, 1])
  x_flatten = tf.reshape(x, [-1, 1])
  r_flatten = tf.concat([d_flatten, x_flatten], 1)
  return tf.reshape(r_flatten, [shape_[0], shape_[1], 2])

In [22]:
x.eval()

array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)

In [23]:
batch_values_to_indices(x).eval()

array([[[0, 1],
        [0, 3],
        [0, 5]],

       [[1, 2],
        [1, 4],
        [1, 6]]], dtype=int32)

In [24]:
#ref = tf.Variable([[1, 2, 3, 4, 5, 6, 7, 8], 
#                   [1, 2, 3, 4, 5, 6, 7, 8]])

#ref = tf.zeros([2, 8], tf.int32)
ref = tf.Variable(tf.zeros([2, 8], tf.int32))

values = tf.constant([[4, 3, 1, 7, 1],
                      [4, 3, 1, 7, 7]])
indices = batch_values_to_indices(values)
updates = tf.constant([[9, 10, 11, 12, 3], 
                       [9, 10, 11, 12, 3]])
add = tf.scatter_nd_add(ref, indices, updates)
sess.run(tf.global_variables_initializer())
print(indices.eval())
print(add.eval())

[[[0 4]
  [0 3]
  [0 1]
  [0 7]
  [0 1]]

 [[1 4]
  [1 3]
  [1 1]
  [1 7]
  [1 7]]]
[[ 0 14  0 10  9  0  0 12]
 [ 0 11  0 10  9  0  0 15]]


In [25]:
indices = [[0, 2], [1, -1]]
depth = 3
on_value = 1.0
off_value = 0.0
axis = -1

In [26]:
tf.one_hot(indices=indices, depth=depth, on_value=on_value, off_value=off_value, axis=axis).eval()

array([[[ 1.,  0.,  0.],
        [ 0.,  0.,  1.]],

       [[ 0.,  1.,  0.],
        [ 0.,  0.,  0.]]], dtype=float32)

In [27]:
tf.one_hot(indices=indices, depth=depth, on_value=on_value, off_value=off_value, axis=axis).eval().shape

(2, 2, 3)

In [28]:
scores = tf.constant([
         [1.2, 3.4], 
         [4.5, 2.1], 
         [4.5, 2.1]
    ])

In [29]:
tf.argmax(scores, 1).eval()

array([1, 0, 0])

In [30]:
tf.arg_max(scores, 1).eval()

array([1, 0, 0])

In [31]:
indices = tf.constant([[1, 3], [4, 2], [6, 2]])

In [32]:
x = tf.argmax(scores, 1)

In [33]:
x.eval().shape

(3,)

In [34]:
y = tf.expand_dims(x, 0)

In [35]:
x.eval()

array([1, 0, 0])

In [36]:
y.eval()

array([[1, 0, 0]])

In [37]:
y.eval().shape

(1, 3)

In [38]:
tf.nn.embedding_lookup(indices, y).eval()

array([[[4, 2],
        [1, 3],
        [1, 3]]], dtype=int32)

In [39]:
 tf.nn.embedding_lookup?

In [40]:
indices.eval()

array([[1, 3],
       [4, 2],
       [6, 2]], dtype=int32)

In [41]:
import melt

tensorflow_version: 1.1.0-rc2


In [42]:
melt.gather_cols(indices, x).eval()

array([[3, 1, 1],
       [2, 4, 4],
       [2, 6, 6]], dtype=int32)

In [43]:
melt.dynamic_last_relevant(indices, x).eval()

IndexError: list index out of range

In [44]:
melt.gather2d(indices, x).eval()

array([3, 4, 6], dtype=int32)