In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
x = tf.constant([
        [1, 3, 2, 0],
        [100, 9, 2, 1024]
    ])

In [6]:
values, indexes = tf.nn.top_k(x, 2)

In [7]:
values.eval()

array([[   3,    2],
       [1024,  100]], dtype=int32)

In [13]:
u = tf.constant([0, 2, 2])

In [14]:
y, idx = tf.unique(u)

In [15]:
y.eval()

array([0, 2], dtype=int32)

In [27]:
#http://stackoverflow.com/questions/37670886/gathering-columns-of-a-2d-tensor-in-tensorflow
def gather_cols(params, indices, name=None):
    """Gather columns of a 2D tensor.

    Args:
        params: A 2D tensor.
        indices: A 1D tensor. Must be one of the following types: ``int32``, ``int64``.
        name: A name for the operation (optional).

    Returns:
        A 2D Tensor. Has the same type as ``params``.
    """
    with tf.name_scope(name, "gather_cols", [params, indices]) as scope:
        # Check input
        params = tf.convert_to_tensor(params, name="params")
        indices = tf.convert_to_tensor(indices, name="indices")
        try:
            params.get_shape().assert_has_rank(2)
        except ValueError:
            raise ValueError('\'params\' must be 2D.')
        try:
            indices.get_shape().assert_has_rank(1)
        except ValueError:
            raise ValueError('\'params\' must be 1D.')

        # Define op
        p_shape = tf.shape(params)
        p_flat = tf.reshape(params, [-1])
        i_flat = tf.reshape(tf.reshape(tf.range(0, p_shape[0]) * p_shape[1],
                                       [-1, 1]) + indices, [-1])
        return tf.reshape(tf.gather(p_flat, i_flat),
                          [p_shape[0], -1])

In [28]:
gather_cols(x, y).eval()

array([[  1,   2],
       [100,   2]], dtype=int32)

In [29]:
s = tf.shape(x)

In [30]:
s[0].eval()

2

In [31]:
s[1].eval()

4

In [32]:
(tf.range(0, s[0])*s[1]).eval()

array([0, 4], dtype=int32)

In [33]:
tf.range(0, s[0]).eval()

array([0, 1], dtype=int32)

In [34]:
tf.reshape(tf.range(0, s[0])*s[1], [-1, 1]).eval()

array([[0],
       [4]], dtype=int32)

In [61]:
(tf.reshape(tf.range(0, s[0])*s[1], [-1, 1]) + y).eval()

array([[0, 2],
       [4, 6]], dtype=int32)

In [36]:
tf.minimum(2,3).eval()

2

In [37]:
y

<tf.Tensor 'Unique_1:0' shape=(?,) dtype=int32>

In [38]:
y.eval()

array([0, 2], dtype=int32)

In [39]:
u.eval()

array([0, 2, 2], dtype=int32)

In [42]:
tf.slice(u, [0], [2]).eval()

array([0, 2], dtype=int32)

In [44]:
u[0:2].eval()

array([0, 2], dtype=int32)

In [48]:
 -tf.nn.top_k(-x, tf.shape(x)[1])[0].eval()

array([[   0,    1,    2,    3],
       [   2,    9,  100, 1024]], dtype=int32)

In [55]:
indexes = tf.constant([0, 1, 3, 5])

In [56]:
top_ids = tf.constant([[0, 2],
           [1, 3]])

In [57]:
tf.nn.embedding_lookup(indexes, top_ids).eval()

array([[0, 3],
       [1, 5]], dtype=int32)

In [ ]:
tf.to