In [1]:
import collections

from tensorflow.contrib.rnn import core_rnn_cell
from tensorflow.contrib.seq2seq.python.ops import beam_search_ops
from tensorflow.contrib.seq2seq.python.ops import decoder
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
from tensorflow.python.framework import tensor_shape
from tensorflow.python.framework import tensor_util
from tensorflow.python.layers import base as layers_base
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import control_flow_ops
from tensorflow.python.ops import embedding_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import nn_ops
from tensorflow.python.ops import tensor_array_ops
from tensorflow.python.util import nest

In [2]:
batch_size = 2

In [3]:
start_tokens = [0] * batch_size

In [4]:
start_tokens

[0, 0, 0]

In [5]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [6]:
start_tokens = tf.convert_to_tensor(start_tokens)

In [7]:
start_tokens.eval()

array([0, 0, 0], dtype=int32)

In [8]:
start_tokens = array_ops.tile(array_ops.expand_dims(start_tokens, 1), [1, 5])

In [10]:
start_tokens.eval().shape

(3, 5)

In [11]:
emb = tf.constant([[1.,2.,3.], [3.,4.,5.]])

In [23]:
tf.nn.embedding_lookup(emb, start_tokens).eval()

array([[[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.]],

       [[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.]],

       [[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.]]], dtype=float32)

In [15]:
s_tokens = tf.constant([0, 0, 0])

In [16]:
input = tf.nn.embedding_lookup(emb, s_tokens)

In [17]:
input.eval().shape

(3, 3)

In [25]:
 array_ops.tile(
        array_ops.expand_dims(input, 1), [1, 5, 1]).eval()

array([[[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.]],

       [[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.]],

       [[ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.],
        [ 1.,  2.,  3.]]], dtype=float32)

In [40]:
y = tf.placeholder(tf.float32, shape = (None,1,3) )
print y.get_shape().as_list()[0]

None


In [41]:
tf.convert_to_tensor(y.get_shape().as_list()[0])

ValueError: None values not supported.

In [43]:
tf.range(10).eval()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [45]:
(tf.range(10) * 3).eval()

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27], dtype=int32)