In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [5]:
input_text = tf.constant([[1, 3, 6], [4, 2, 5]])

In [7]:
scores = tf.constant([[0.3, 0.6, 0.1], [0.7, 0.1, 0.2]])

In [8]:
import melt

tensorflow_version: 1.1.0-rc2


In [21]:
u = tf.arg_max(scores, 1)

In [22]:
u.eval()

array([1, 0])

In [11]:
melt.gather2d(input_text, tf.cast(tf.argmax(scores, 1), dtype=tf.int32)).eval()

array([3, 4], dtype=int32)

In [12]:
top_logprobs, top_ids = tf.nn.top_k(scores, 2)

In [13]:
top_logprobs.eval()

array([[ 0.60000002,  0.30000001],
       [ 0.69999999,  0.2       ]], dtype=float32)

In [15]:
top_ids.eval()

array([[1, 0],
       [0, 2]], dtype=int32)

In [16]:
top_ids = tf.nn.embedding_lookup(input_text, top_ids)

In [24]:
tf.nn.embedding_lookup(input_text[0], u).eval()

array([3, 1], dtype=int32)

In [25]:
input_text[0].eval()

array([1, 3, 6], dtype=int32)

In [27]:
scores = scores[0]

In [28]:
input_text = input_text[0]

In [29]:
top_logprobs, top_ids = tf.nn.top_k(scores, 2)

In [30]:
top_ids.eval()

array([1, 0], dtype=int32)