In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
import numpy as np

from tensorflow.contrib.rnn import core_rnn_cell
from tensorflow.contrib.seq2seq.python.ops import attention_wrapper
from tensorflow.contrib.seq2seq.python.ops import beam_search_decoder
from tensorflow.contrib.seq2seq.python.ops import beam_search_ops
from tensorflow.contrib.seq2seq.python.ops import decoder
from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
from tensorflow.python.layers import core as layers_core
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import nn_ops
from tensorflow.python.ops import variables
from tensorflow.python.platform import test

In [3]:
probs = tf.constant([
        [[-.2, -.2, -.2, -.2, -.2], [-.3, -.3, -.3, 3, 0], [5, 6, 0, 0, 0]],
        [[-.2, -.2, -.2, -.2, 0], [-.3, -.3, -.1, 3, 0], [5, 6, 3, 0, 0]],
    ])

In [4]:
probs.eval()

array([[[-0.2       , -0.2       , -0.2       , -0.2       , -0.2       ],
        [-0.30000001, -0.30000001, -0.30000001,  3.        ,  0.        ],
        [ 5.        ,  6.        ,  0.        ,  0.        ,  0.        ]],

       [[-0.2       , -0.2       , -0.2       , -0.2       ,  0.        ],
        [-0.30000001, -0.30000001, -0.1       ,  3.        ,  0.        ],
        [ 5.        ,  6.        ,  3.        ,  0.        ,  0.        ]]], dtype=float32)

In [6]:
eos_token = 0
previously_finished = constant_op.constant(
        [[0, 1, 0], [0, 1, 1]], dtype=dtypes.float32)
masked = beam_search_decoder._mask_probs(probs, eos_token,
                                         previously_finished)

In [7]:
masked.eval()

array([[[ -2.00000003e-01,  -2.00000003e-01,  -2.00000003e-01,
          -2.00000003e-01,  -2.00000003e-01],
        [  0.00000000e+00,  -3.40282347e+38,  -3.40282347e+38,
          -3.40282347e+38,  -3.40282347e+38],
        [  5.00000000e+00,   6.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00]],

       [[ -2.00000003e-01,  -2.00000003e-01,  -2.00000003e-01,
          -2.00000003e-01,   0.00000000e+00],
        [  0.00000000e+00,  -3.40282347e+38,  -3.40282347e+38,
          -3.40282347e+38,  -3.40282347e+38],
        [  0.00000000e+00,  -3.40282347e+38,  -3.40282347e+38,
          -3.40282347e+38,  -3.40282347e+38]]], dtype=float32)

In [8]:
probs.eval().shape

(2, 3, 5)

In [9]:
previously_finished.eval()

array([[ 0.,  1.,  0.],
       [ 0.,  1.,  1.]], dtype=float32)

In [10]:
previously_finished.eval().shape

(2, 3)