In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
# pylint: enable=unused-import

import numpy as np

from tensorflow.contrib.seq2seq.python.ops import beam_search_ops
from tensorflow.python.framework import ops
from tensorflow.python.platform import test


def _transpose_batch_time(x):
  return np.transpose(x, [1, 0, 2]).astype(np.int32)

In [2]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [3]:
# (max_time = 4, batch_size = 1, beams = 3)
step_ids = _transpose_batch_time([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [-1, -1, -1]]])
parent_ids = _transpose_batch_time([[[0, 0, 0], [2, 1, 1], [2, 2, 2], [-1, -1, -1]]])
sequence_length = [[3, 3, 3]]

In [4]:
step_ids

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[-1, -1, -1]]], dtype=int32)

In [5]:
step_ids.shape

(4, 1, 3)

In [6]:
parent_ids

array([[[ 0,  0,  0]],

       [[ 2,  1,  1]],

       [[ 2,  2,  2]],

       [[-1, -1, -1]]], dtype=int32)

In [7]:
sequence_length

[[3, 3, 3]]

In [8]:
expected_result = _transpose_batch_time([[[2, 2, 2], [6, 5, 6], [7, 8, 9], [-1, -1, -1]]])

In [9]:
expected_result

array([[[ 2,  2,  2]],

       [[ 6,  5,  6]],

       [[ 7,  8,  9]],

       [[-1, -1, -1]]], dtype=int32)

In [10]:
beams = beam_search_ops.gather_tree(
        step_ids=step_ids, parent_ids=parent_ids,
        sequence_length=sequence_length)

In [11]:
beams.eval()

array([[[ 2,  2,  2]],

       [[ 6,  6,  6]],

       [[ 7,  8,  9]],

       [[-1, -1, -1]]], dtype=int32)

In [16]:
beams[0].eval()

array([[2, 2, 2]], dtype=int32)

In [17]:
beams2 = tf.transpose(beams, [1, 2, 0])

In [18]:
beams2[0].eval()

array([[ 2,  6,  7, -1],
       [ 2,  6,  8, -1],
       [ 2,  6,  9, -1]], dtype=int32)