In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [4]:
t = tf.constant([[1,2,3],
                 [4,5,6]])
multiplier = 4

In [6]:
import collections

from tensorflow.contrib.rnn import core_rnn_cell
from tensorflow.contrib.seq2seq.python.ops import beam_search_ops
from tensorflow.contrib.seq2seq.python.ops import decoder
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
from tensorflow.python.framework import tensor_shape
from tensorflow.python.framework import tensor_util
from tensorflow.python.layers import base as layers_base
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import control_flow_ops
from tensorflow.python.ops import embedding_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import nn_ops
from tensorflow.python.ops import tensor_array_ops
from tensorflow.python.util import nest

In [9]:
    t = ops.convert_to_tensor(t, name="t")
    shape_t = array_ops.shape(t)
    if t.shape.ndims is None or t.shape.ndims < 1:
      raise ValueError("t must have statically known rank")
    tiling = [1] * (t.shape.ndims + 1)
    tiling[1] = multiplier
    tiled_static_batch_size = (
        t.shape[0].value * multiplier if t.shape[0].value is not None else None)
    tiled = array_ops.tile(array_ops.expand_dims(t, 1), tiling)
    tiled = array_ops.reshape(
        tiled, array_ops.concat(([shape_t[0] * multiplier], shape_t[1:]), 0))
    tiled.set_shape(
        tensor_shape.TensorShape(
            [tiled_static_batch_size]).concatenate(t.shape[1:]))

In [10]:
tiled.eval()

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]], dtype=int32)

In [12]:
tiling

[1, 4, 1]

In [13]:
tiled2 = array_ops.tile(array_ops.expand_dims(t, 1), tiling)

In [14]:
tiled2.eval()

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]]], dtype=int32)

In [15]:
array_ops.expand_dims(t, 1).eval()

array([[[1, 2, 3]],

       [[4, 5, 6]]], dtype=int32)

In [16]:
array_ops.expand_dims(t, 1).eval().shape

(2, 1, 3)

In [17]:
array_ops.expand_dims(t, 1)[0].eval()

array([[1, 2, 3]], dtype=int32)

In [18]:
array_ops.expand_dims(t, 1)[0][0].eval()

array([1, 2, 3], dtype=int32)