In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
def index_matrix_to_pairs(index_matrix):
  # [[3,1,2], [2,3,1]] -> [[[0, 3], [1, 1], [2, 2]], 
  #                        [[0, 2], [1, 3], [2, 1]]]
  replicated_first_indices = tf.range(tf.shape(index_matrix)[0])
  rank = len(index_matrix.get_shape())
  if rank == 2:
    replicated_first_indices = tf.tile(
        tf.expand_dims(replicated_first_indices, dim=1),
        [1, tf.shape(index_matrix)[1]])
  return tf.stack([replicated_first_indices, index_matrix], axis=rank)

In [4]:
x = tf.constant([[3,1,2], [2,3,1]])
x.eval()

array([[3, 1, 2],
       [2, 3, 1]], dtype=int32)

In [5]:
index_matrix_to_pairs(x).eval()

array([[[0, 3],
        [0, 1],
        [0, 2]],

       [[1, 2],
        [1, 3],
        [1, 1]]], dtype=int32)

In [6]:
index_matrix = x

In [7]:
replicated_first_indices = tf.range(tf.shape(index_matrix)[0])

In [8]:
replicated_first_indices.eval()

array([0, 1], dtype=int32)

In [9]:
tf.expand_dims(replicated_first_indices, dim=1).eval()

array([[0],
       [1]], dtype=int32)

In [10]:
replicated_first_indices

<tf.Tensor 'range_1:0' shape=(?,) dtype=int32>

In [11]:
def batch_values_to_indices(x):
  shape_ = tf.shape(x)
  batch_size = shape_[0]
  num_cols = shape_[1]
  d = tf.transpose(tf.expand_dims(tf.range(batch_size),0))
  d = tf.tile(d, [1, num_cols])
  d_flatten = tf.reshape(d, [-1, 1])
  x_flatten = tf.reshape(x, [-1, 1])
  r_flatten = tf.concat([d_flatten, x_flatten], 1)
  return tf.reshape(r_flatten, [shape_[0], shape_[1], 2])

In [12]:
batch_values_to_indices(index_matrix).eval()

array([[[0, 3],
        [0, 1],
        [0, 2]],

       [[1, 2],
        [1, 3],
        [1, 1]]], dtype=int32)

In [13]:
 tf.tile(
        tf.expand_dims(replicated_first_indices, dim=1),
        [1, tf.shape(index_matrix)[1]]).eval()

array([[0, 0, 0],
       [1, 1, 1]], dtype=int32)

In [14]:
replicated_first_indices =  tf.tile(
        tf.expand_dims(replicated_first_indices, dim=1),
        [1, tf.shape(index_matrix)[1]]).eval()

In [15]:
tf.stack([replicated_first_indices, index_matrix], axis=2).eval()

array([[[0, 3],
        [0, 1],
        [0, 2]],

       [[1, 2],
        [1, 3],
        [1, 1]]], dtype=int32)

In [16]:
tf.stack([replicated_first_indices, index_matrix], axis=1).eval()

array([[[0, 0, 0],
        [3, 1, 2]],

       [[1, 1, 1],
        [2, 3, 1]]], dtype=int32)

In [18]:
values = tf.constant([[1,2,3,4], [5,6,7,8]])

In [19]:
values.eval()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

In [20]:
tf.gather_nd(values, batch_values_to_indices(index_matrix)).eval()

array([[4, 2, 3],
       [7, 8, 6]], dtype=int32)